# Generated by Django 4.1 on 2022-09-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_book_movieinstance_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='summary',
            new_name='synopsis',
        ),
    ]
