# Generated by Django 4.1 on 2022-09-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_summary_movie_synopsis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Director',
        ),
    ]
