# Generated by Django 4.1 on 2022-09-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_author_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='author',
            new_name='director',
        ),
    ]
