# Generated by Django 4.1 on 2022-09-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_author_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('Н', 'Нет наличии'), ('В', 'Взят'), ('Д', 'Доступен'), ('З', 'Зарезервирован')], default='Д', help_text='Доступность фильмов', max_length=1),
        ),
    ]
